DROP TABLE IF EXISTS workoutData;

CREATE TABLE workoutData(
    id serial PRIMARY KEY,
    pullupSet1 integer,
    pullUpSet1Wt integer,
    pullupSet2 integer,
    pullUpSet2Wt integer,
    pullupSet3 integer,
    pullUpSet3Wt integer,
    pullupSet4 integer,
    pullUpSet4Wt integer,
    pullupSet5 integer,
    pullUpSet5Wt integer,
    pullUpTime TIME NOT NULL,
    dipSet1 integer,
    dipSet1Wt integer,
    dipSet2 integer,
    dipSet2Wt integer,
    dipSet3 integer,
    dipSet3Wt integer,
    dipSet4 integer,
    dipSet4Wt integer,
    dipSet5 integer,
    dipSet5Wt integer,
    dipTime TIME NOT NULL,
    squatSet1 integer,
    squatSet1Wt integer,
    squatSet2 integer,
    squatSet2Wt integer,
    squatSet3 integer,
    squatSet3Wt integer,
    squatSet4 integer,
    squatSet4Wt integer,
    squatSet5 integer,
    squatSet5Wt integer,
    squatTime TIME NOT NULL,
    wkDate DATE NOT NULL DEFAULT CURRENT_DATE
);