###
GET http://localhost:3000

###
GET http://localhost:3000/api/workout

###
POST http://localhost:3000/api/workout
Content-Type: application/json

{
 "date": "2023-04-30",
 "name": "pullups",
 "reps": 10,
 "weight": 180,
 "duration": 0
}

###
DELETE http://localhost:3000/api/workout
Content-Type: application/json

{
 "id": 2
}
